# Generated by Django 4.2.7 on 2025-02-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_inquiry_created_at_remove_inquiry_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
    ]
