version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "Bullshit03Sasano19"
      MYSQL_DATABASE: "portfolio_db"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    build: .
    container_name: portfolio_web
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9132:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings"
      DB_HOST: db  # 'db' に統一
      DB_PORT: "3306"
      DB_NAME: portfolio_db
      DB_USER: root
      DB_PASSWORD: 'Bullshit03Sasano19'
    networks:
      - portfolio_network

volumes:
  db_data: {}

networks:
  portfolio_network: