# Generated by Django 4.2.7 on 2025-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', '有効'), ('inactive', '無効')], default='active', max_length=8, verbose_name='ステータス'),
        ),
    ]
