# Generated by Django 5.1.6 on 2025-02-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_likes_received_alter_like_liked_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='likes_received',
            field=models.ManyToManyField(related_name='received_likes_custom', to=settings.AUTH_USER_MODEL, verbose_name='いいねを受け取ったユーザー'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
