# Generated by Django 5.1.6 on 2025-02-12 17:13

from django.db import migrations, models, connection

def add_name_column(apps, schema_editor):
    table = 'accounts_generaluserprofile'
    column = 'name'
    with connection.cursor() as cursor:
        # MySQL 用にカラムが存在するかチェック
        cursor.execute("SHOW COLUMNS FROM `{}` LIKE %s".format(table), [column])
        result = cursor.fetchone()
        if not result:
            # カラムが存在しなければ追加する
            cursor.execute("ALTER TABLE `{}` ADD COLUMN `{}` VARCHAR(255) NULL".format(table, column))

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluserprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='furigana',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名前'),
        ),
    ]
