# Generated by Django 5.1.6 on 2025-02-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_generaluserprofile_age_generaluserprofile_bio_and_more'),
    ]

    operations = [
    ]
