# Generated by Django 5.1.6 on 2025-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_furigana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='furigana',
            field=models.CharField(max_length=255, verbose_name='ふりがな'),
        ),
    ]
